In [1]:
!conda list numpy

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.14.3           py36h9fa60d3_1  
numpy-base                1.14.3           py36h555522e_1  
numpydoc                  0.8.0                    py36_0  


In [2]:
import time
import numpy as np

In [5]:
x = np.random.random(100000000)

In [6]:
start = time.time()
sum(x)/len(x)
print(time.time()-start)

28.635915517807007


In [7]:
start = time.time()
np.mean(x)
print(time.time()-start)

0.19934463500976562


In [8]:
x = np.array([1,2,3,4,5])

In [14]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
x.shape

(5,)

In [15]:
x.dtype

dtype('int32')

In [16]:
x.shape

(5,)

In [17]:
x.size

5

In [29]:
y = np.array([[1,2,3,4,5],[1,2,3.0,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [30]:
print(y)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [31]:
y.dtype

dtype('float64')

In [32]:
y.shape

(4, 5)

In [33]:
y.size

20

In [34]:
z = np.array([1,2,"hello world"])

In [35]:
print(z)

['1' '2' 'hello world']


In [36]:
z.dtype

dtype('<U11')

In [37]:
z.shape

(3,)

In [38]:
z.size

3

In [43]:
x = np.array([1, 2, 3.1, 4.0, 5], dtype = np.int32)

In [44]:
x.dtype

dtype('int32')

In [45]:
print(x)

[1 2 3 4 5]


In [48]:
x = np.array([0, 1, 1, 0, 1, 0], dtype = np.bool_)

In [49]:
x.dtype

dtype('bool')

In [50]:
print(x)

[False  True  True False  True False]
