# numpy ndarray 之内功心法，理解高维操作！

https://mp.weixin.qq.com/s/qMiNGHHZMnPeFqXFz9c6rQ

In [1]:
import numpy as np

In [4]:
data_1d = np.array([0, 1, 2, 3])
data_2d = np.arange(6).reshape(2,3)
data_3d = np.arange(24).reshape(2,3,4)
print(data_1d)
print(data_2d)
print(data_3d)

[0 1 2 3]
[[0 1 2]
 [3 4 5]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
print(data_3d.ndim)
print(data_3d.shape)

3
(2, 3, 4)


## 1.关于图像的数据结构

In [6]:
import matplotlib.pylab as plt

image = plt.imread("rainbow.jpg")
print(image.shape)

(480, 640, 3)


图片大小是640 x 480，也就是宽640，高480。但是读取到数据结构里面的时候是先高后宽，第三个维度表示颜色（R,G,B）

In [10]:
print(image[100,100])

[177 191 202]


## 2.对于高于3维的数据的理解

用 shape 属性返回的元组，从左到右，座标轴分别命名为 axis 0, axis 1, ...，请注意，现在是从左向右数，正好是这个元组的 index，在以后的运算中，都按此规定。

#### 抽象座标轴顺序从左向右。指定哪个轴，就只在哪个轴向操作，其他轴不受影响。

### 1)排序（sorting）

In [26]:
data = np.arange(12)
np.random.shuffle(data)
data = data.reshape(3,4)
data

array([[ 5,  8,  6,  0],
       [10,  1,  9,  4],
       [ 2, 11,  7,  3]])

In [27]:
print(np.sort(data, axis = 0))

[[ 2  1  6  0]
 [ 5  8  7  3]
 [10 11  9  4]]


In [28]:
print(np.sort(data, axis = 1))

[[ 0  5  6  8]
 [ 1  4  9 10]
 [ 2  3  7 11]]


### 2)求和、均值、方差、最大、最小、累加、累乘

这几个函数调用，一般会指定轴向，sum，mean，std，var，min，max 会导致这个轴被压扁，缩减为一个数值

In [30]:
print(data_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [32]:
print(np.sum(data_3d, axis = 0))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [33]:
print(np.sum(data_3d, axis = 1))

[[12 15 18 21]
 [48 51 54 57]]


In [34]:
print(np.sum(data_3d, axis = 2))

[[ 6 22 38]
 [54 70 86]]


In [36]:
print(np.mean(data_3d, axis = 1))

[[ 4.  5.  6.  7.]
 [16. 17. 18. 19.]]


In [37]:
print(np.std(data_3d, axis = 1))

[[3.26598632 3.26598632 3.26598632 3.26598632]
 [3.26598632 3.26598632 3.26598632 3.26598632]]


cumsum，cumprod 不缩减轴向，只在指定轴向操作

In [38]:
print(np.cumsum(data_3d, axis = 1))

[[[ 0  1  2  3]
  [ 4  6  8 10]
  [12 15 18 21]]

 [[12 13 14 15]
  [28 30 32 34]
  [48 51 54 57]]]


### 3)索引和切片
#### 在索引中出现冒号(:)，则本轴继续存在，如果只是一个数值，则本轴消失。

In [39]:
print(data_3d[0, :, :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
print(data_3d[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [41]:
print(data_3d[0,1,2])

6


In [42]:
print(data_3d[0:1, 1:2, 2:3])

[[[6]]]


In [43]:
data_3d[0,1,2].shape

()

In [46]:
data_3d[0,1,2].ndim

0

In [44]:
data_3d[0:1, 1:2, 2:3].shape

(1, 1, 1)

In [45]:
data_3d[0:1, 1:2, 2:3].ndim

3

### 4)拼接
指定那个轴就在哪个轴向拼接

In [48]:
data1 = np.arange(4).reshape(2,2)
print(np.concatenate([data1,data1], axis = 0))

[[0 1]
 [2 3]
 [0 1]
 [2 3]]


In [49]:
print(np.concatenate([data1,data1], axis = 1))

[[0 1 0 1]
 [2 3 2 3]]


## 3.关于reshape
#### ndarray 的数据在内存里以一维线性存放，reshape 前后，数据没有变化，只是访问方式变了而已。

In [54]:
data1 = np.arange(24)
data_3d = data1.reshape(2,3,4)
print(data_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


数据先按照axis0=2分成2组

In [56]:
data2 = data1.reshape(2,12)
data2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

然后分别将前面两组数据按照axis1=3分成3组。

In [57]:
data3 = data2[0].reshape(3,4)
data3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])